apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Zone Edit and Read permissions are required
  api-token: <cf_api_token>
